AllCops:
  TargetRubyVersion: 3.2.2
  SuggestExtensions: false
  NewCops: enable
  Exclude:
  - 'bin/**/*'
  - 'db/**/*'
  - 'config/**/*'
  - 'node_modules/**/*'
  - 'script/**/*'
  - 'support/**/*'
  - 'tmp/**/*'
  - 'test/**/*'
  - 'vendor/**/*'
  - 'spec/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
Layout/LineLength:
  Max: 80
Metrics/MethodLength:
  Max: 40
  CountComments: false
Metrics/ClassLength:
  Max: 250
  CountComments: false
Metrics/ModuleLength:
  Max: 150
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  CountComments: false
  Max: 30
Naming/MethodParameterName:
  MinNameLength: 1
