- id: 200
  main: Thunderstorm
  description: 200
  icon: 11d
- id: 201
  main: Thunderstorm
  description: 201
  icon: 11d
- id: 202
  main: Thunderstorm
  description: 202
  icon: 11d
- id: 210
  main: Thunderstorm
  description: 210
  icon: 11d
- id: 211
  main: Thunderstorm
  description: 211
  icon: 11d
- id: 212
  main: Thunderstorm
  description: 212
  icon: 11d
- id: 221
  main: Thunderstorm
  description: 221
  icon: 11d
- id: 230
  main: Thunderstorm
  description: 230
  icon: 11d
- id: 231
  main: Thunderstorm
  description: 231
  icon: 11d
- id: 232
  main: Thunderstorm
  description: 232
  icon: 11d
- id: 300
  main: Drizzle
  description: 300
  icon: 09d
- id: 301
  main: Drizzle
  description: 301
  icon: 09d
- id: 302
  main: Drizzle
  description: 302
  icon: 09d
- id: 310
  main: Drizzle
  description: 310
  icon: 09d
- id: 311
  main: Drizzle
  description: 311
  icon: 09d
- id: 312
  main: Drizzle
  description: 312
  icon: 09d
- id: 313
  main: Drizzle
  description: 313
  icon: 09d
- id: 314
  main: Drizzle
  description: 314
  icon: 09d
- id: 321
  main: Drizzle
  description: 321
  icon: 09d
- id: 500
  main: Rain
  description: 500
  icon: 10d
- id: 501
  main: Rain
  description: 501
  icon: 10d
- id: 502
  main: Rain
  description: 502
  icon: 10d
- id: 503
  main: Rain
  description: 503
  icon: 10d
- id: 504
  main: Rain
  description: 504
  icon: 10d
- id: 511
  main: Rain
  description: 511
  icon: 13d
- id: 520
  main: Rain
  description: 520
  icon: 09d
- id: 521
  main: Rain
  description: 521
  icon: 09d
- id: 522
  main: Rain
  description: 522
  icon: 09d
- id: 531
  main: Rain
  description: 531
  icon: 09d
- id: 600
  main: Snow
  description: 600
  icon: 13d
- id: 601
  main: Snow
  description: 601
  icon: 13d
- id: 602
  main: Snow
  description: 602
  icon: 13d
- id: 611
  main: Snow
  description: 611
  icon: 13d
- id: 612
  main: Snow
  description: 612
  icon: 13d
- id: 613
  main: Snow
  description: 613
  icon: 13d
- id: 615
  main: Snow
  description: 615
  icon: 13d
- id: 616
  main: Snow
  description: 616
  icon: 13d
- id: 620
  main: Snow
  description: 620
  icon: 13d
- id: 621
  main: Snow
  description: 621
  icon: 13d
- id: 622
  main: Snow
  description: 622
  icon: 13d
- id: 701
  main: Mist
  description: 701
  icon: 50d
- id: 711
  main: Smoke
  description: 711
  icon: 50d
- id: 721
  main: Haze
  description: 701
  icon: 50d
- id: 731
  main: Dust
  description: 731
  icon: 50d
- id: 741
  main: Fog
  description: 741
  icon: 50d
- id: 751
  main: Sand
  description: 751
  icon: 50d
- id: 761
  main: Dust
  description: 761
  icon: 50d
- id: 762
  main: Ash
  description: 701
  icon: 50d
- id: 771
  main: Squalls
  description: 711
  icon: 50d
- id: 781
  main: Tornado
  description: 781
  icon: 50d
- id: 800
  main: Clear
  description: 800
  icon: 01d
- id: 801
  main: Clouds
  description: 801
  icon: 02d
- id: 802
  main: Clouds
  description: 802
  icon: 03d
- id: 803
  main: Clouds
  description: 803
  icon: 04d
- id: 804
  main: Clouds
  description: 804
  icon: 04d
