defaults: &defaults
  airport_types_to_import:
    - small_airport
    - medium_airport
    - large_airport
  airport_countries_to_import:
    - FR
    - LU
    - DE
    - NL
    - DK
  airports_white_list:
    - LFJY
  weather_profiles:
    - safe:
        - 210
        - 800
        - 801
        - 802
    - adventurous:
        - 300
        - 310
        - 500
        - 501
        - 520
        - 600
        - 803
        - 804
  # Next cycle: 12_NOV_2023
  sia_current_cycle: 05_OCT_2023

development:
  <<: *defaults
  default_weather_calls_validity_hours: 8
  default_weather_tile_precision: 1
  default_weather_tile_depth: 6
  fake_weather: true

test:
  <<: *defaults
  default_weather_calls_validity_hours: 8
  default_weather_tile_precision: 1
  default_weather_tile_depth: 4
  fake_weather: true

production:
  <<: *defaults
  default_weather_calls_validity_hours: 8
  default_weather_tile_precision: 1
  default_weather_tile_depth: 4
  fake_weather: false

staging:
  <<: *defaults
  default_weather_calls_validity_hours: 2
  default_weather_tile_precision: 1
  default_weather_tile_depth: 4
  fake_weather: false
