defaults: &defaults
  # Accepted values: 1, 0.5 and 0.25
  default_weather_tile_precision: 1
  contact_form_recipient: alex@sky-unlimited.lu
  airport_types_to_import:
    - small_airport
    - medium_airport
    - large_airport
  airport_countries_to_import:
    - FR
    - LU
    - DE
    - NL
    - DK
  airports_white_list:
    - LFJY
    - EKSB
  weather_tiles_left_limit: -5
  weather_tiles_right_limit: 16
  weather_tiles_upper_limit: 58
  weather_tiles_lower_limit: 41
  weather_profiles:
    - safe:
        - 210
        - 800
        - 801
        - 802
    - adventurous:
        - 300
        - 310
        - 500
        - 501
        - 520
        - 803
        - 804

development:
  <<: *defaults
  weather_cache_expire_hour: 12
  default_weather_tile_depth: 6

test:
  <<: *defaults
  weather_cache_expire_hour: 12
  default_weather_tile_depth: 4

production:
  <<: *defaults
  weather_cache_expire_hour: 12
  contact_form_recipient: contact@sky-unlimited.lu
  default_weather_tile_depth: 6

staging:
  <<: *defaults
  contact_form_recipient: contact@sky-unlimited.lu
  weather_cache_expire_hour: 12
  default_weather_tile_precision: 1
  default_weather_tile_depth: 6
